# Copyright (C) Alif Semiconductor - All Rights Reserved.
# Use, distribution and modification of this code is permitted under the
# terms stated in the Alif Semiconductor Software License Agreement
#
# You should have received a copy of the Alif Semiconductor Software
# License Agreement with this file. If not, please write to:
# contact@alifsemi.com, or visit: https://alifsemi.com/license

# Enable LPGPIO wakeup source
CONFIG_LPGPIO_WAKEUP_ENABLED=y
CONFIG_LPGPIO_WAKEUP_SOURCE=1

# Enable M55 LPGPIO IRQ callback
CONFIG_LPGPIO_M55_IRQ_ENABLED=y
CONFIG_LPGPIO_M55_IRQ_EDGE_FALLING=y

# How long the system should wait before entering sleep
CONFIG_WAIT_BEFORE_SLEEP_SECONDS=0
# Sleep until LPGPIO wakeup event occurs (disable RTC timer wakeup)
CONFIG_SLEEP_TIME_DISCONNECTED=0
