# SPDX-FileCopyrightText: Copyright Alif Semiconductor
# SPDX-License-Identifier: Apache-2.0

# USB device MSC support
CONFIG_USB_DEVICE_STACK_NEXT=y

CONFIG_STDOUT_CONSOLE=y
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_USBD_MSC_CLASS=y
CONFIG_USBD_MSC_LUNS_PER_INSTANCE=3

CONFIG_LOG=y
CONFIG_USBD_LOG_LEVEL_WRN=y
CONFIG_UDC_DRIVER_LOG_LEVEL_WRN=y

CONFIG_SAMPLE_USBD_PID=0x0008
CONFIG_SAMPLE_USBD_PRODUCT="USBD MSC sample"
CONFIG_MAIN_STACK_SIZE=2048

# MSC OSPI Flash App Configuration
CONFIG_APP_MSC_STORAGE_FLASH_FATFS=y

# OSPI driver configuration
CONFIG_FLASH=y

# SD card App support
CONFIG_APP_MSC_STORAGE_SDCARD=y

# FATFS
CONFIG_FS_FATFS_WINDOW_ALIGNMENT=512
CONFIG_FS_FATFS_LFN=y
CONFIG_FS_LOG_LEVEL_INF=y

# SDHC LOG
CONFIG_SDHC_LOG_LEVEL_INF=y

# SDHC DMA
CONFIG_SDHC_RSP_136_HAS_CRC=y
CONFIG_INTEL_EMMC_HOST=y
CONFIG_INTEL_EMMC_HOST_DMA=y
CONFIG_INTEL_EMMC_HOST_ADMA=y
