# Copyright (C) 2026 Alif Semiconductor - All Rights Reserved.
# Use, distribution and modification of this code is permitted under the
# terms stated in the Alif Semiconductor Software License Agreement
#
# You should have received a copy of the Alif Semiconductor Software
# License Agreement with this file. If not, please write to:
# contact@alifsemi.com, or visit: https://alifsemi.com/license

# Video subsystem
CONFIG_VIDEO=y
CONFIG_VIDEO_JPEG_HANTRO_VC9000E=y
CONFIG_USE_ALIF_JPEG_SW_HEADER_LIB=y
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=2
CONFIG_VIDEO_BUFFER_POOL_SZ_MAX=1382400

# Logging
CONFIG_LOG=y
CONFIG_VIDEO_LOG_LEVEL_INF=y
