# Copyright (C) Alif Semiconductor - All Rights Reserved.
# Use, distribution and modification of this code is permitted under the
# terms stated in the Alif Semiconductor Software License Agreement
#
# You should have received a copy of the Alif Semiconductor Software
# License Agreement with this file. If not, please write to:
# contact@alifsemi.com, or visit: https: //alifsemi.com/license
#

CONFIG_VIDEO_BUFFER_POOL_SZ_MAX=114688
CONFIG_VIDEO_BUFFER_POOL_NUM_MAX=6
CONFIG_USE_ALIF_ISP_LIB=y
CONFIG_ISP_LIB_SCALAR_MODULE=y
CONFIG_ISP_LIB_DMSC_MODULE=y
CONFIG_ISP_LIB_CCM_MODULE=n
CONFIG_ISP_LIB_WBM_MODULE=n
CONFIG_ISP_LIB_WB_MODULE=n
