# Copyright (C) 2025 Alif Semiconductor - All Rights Reserved.
# Use, distribution and modification of this code is permitted under the
# terms stated in the Alif Semiconductor Software License Agreement
#
# You should have received a copy of the Alif Semiconductor Software
# License Agreement with this file. If not, please write to:
# contact@alifsemi.com, or visit: https://alifsemi.com/license


CONFIG_STDOUT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_ARM_MPU=y
CONFIG_MEMC=y
CONFIG_MEMC_OSPI_ALIF=y
CONFIG_USE_ALIF_HAL_OSPI=y
CONFIG_EVENTS=y
CONFIG_LOG=y
