# Copyright (C) Alif Semiconductor.
# SPDX-License-Identifier: Apache-2.0

CONFIG_STDOUT_CONSOLE=y
CONFIG_FLASH=y
CONFIG_LOG=y
CONFIG_EVENTS=y
CONFIG_MAIN_STACK_SIZE=8192
CONFIG_FLASH_LOG_LEVEL_DBG=n

#For Enable XiP
CONFIG_ALIF_OSPI_FLASH_XIP=n

#For Booting image in XiP mode from flash
CONFIG_ALIF_OSPI_FLASH_BOOT_XIP_IMAGE=n
