# Camera
CONFIG_VIDEO=y
CONFIG_LOG=y
CONFIG_PRINTK=y
CONFIG_STDOUT_CONSOLE=y
CONFIG_I2C_TARGET=y
CONFIG_I2C=y
CONFIG_I2C_DW_CLOCK_SPEED=100
CONFIG_SYS_HEAP_AUTO=y
CONFIG_VIDEO_LOG_LEVEL_DBG=n
CONFIG_GPIO=y
# AIPL (Alif Image Processing Library) - for HW-accelerated color conversion
CONFIG_AIPL=y
CONFIG_AIPL_COLOR_CONVERSION=y
CONFIG_AIPL_CONVERT_I420=y
CONFIG_AIPL_CONVERT_I420_TO_RGB565=y
CONFIG_AIPL_DEMOSAICING=y
CONFIG_AIPL_HELIUM_ACCELERATION=y
CONFIG_DAVE2D=n
CONFIG_AIPL_DAVE2D_ACCELERATION=n
# Display
CONFIG_DISPLAY=y
CONFIG_MIPI_DSI=y
CONFIG_HEAP_MEM_POOL_SIZE=81920
